/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.BangDatTour;

/**
 *
 * @author NCT99
 */
public class bangDatTourPanel extends javax.swing.JPanel {

    /**
     * Creates new form bangDatTourPanel
     */
    DefaultTableModel modelTableVd ;
    public bangDatTourPanel(ArrayList<BangDatTour> listBDT) {
        initComponents();
        modelTableVd=(DefaultTableModel) jTablebdtVD.getModel();
        String ngay;
        
        for (BangDatTour itemBDT : listBDT) { 
           // System.out.print("\n "+itemBDT.getKieuTour()+"  : "+itemBDT.getIntKieuTour());
            ngay=itemBDT.getNgayBatDau().getDate()+"/"+((itemBDT.getNgayBatDau().getMonth()==0)?12:itemBDT.getNgayBatDau().getMonth())
               +"/"+((itemBDT.getNgayBatDau().getMonth()==0)?itemBDT.getNgayBatDau().getYear()-1:itemBDT.getNgayBatDau().getYear());
             modelTableVd.addRow(new Object[]{//
           itemBDT.getMaTour(), itemBDT.getMaKH(),itemBDT.getSoLuongNguoi(),ngay,
                 itemBDT.getKieuTour(),itemBDT.getKieuKH(),itemBDT.getThanhTien()
                 
        });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablebdtVD = new javax.swing.JTable();

        jTablebdtVD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tour", "Mã KH", "Số Lượng", "Ngày Bắt Đầu", "Kiểu Tour", "Kiểu kH", "Tổng Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablebdtVD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablebdtVD;
    // End of variables declaration//GEN-END:variables
}
