/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.event.ItemEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import model.*;

/**
 *
 * @author NCT99
 */
public class DatTourPanel extends javax.swing.JPanel {

    /**
     * Creates new form DatTourPanel
     */
    DocGhiFile<Tour> dsTour;
     DocGhiFile<KhachHang> dsKH;
     DocGhiFile<BangDatTour> dsBangDatTour;
     DefaultTableModel modelTabel ;
     double tongTienTatCa=0.0;
    public DatTourPanel() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
         dsTour=new DocGhiFile<>();
        dsKH=new DocGhiFile<>();
        dsBangDatTour=new DocGhiFile<>();
         modelTabel=(DefaultTableModel) jTableBDT.getModel();        
        dsTour.docfile("tour.dat");
        dsKH.docfile("khachhang.dat");
        dsBangDatTour.docfile("bangdattour.dat");
        String ngay;
        for (BangDatTour itemBDT : dsBangDatTour.getListDT()) {
            tongTienTatCa+=itemBDT.getThanhTien();
            ngay=itemBDT.getNgayBatDau().getDate()+"/"+((itemBDT.getNgayBatDau().getMonth()==0)?12:itemBDT.getNgayBatDau().getMonth())
               +"/"+((itemBDT.getNgayBatDau().getMonth()==0)?itemBDT.getNgayBatDau().getYear()-1:itemBDT.getNgayBatDau().getYear());
             modelTabel.addRow(new Object[]{//
           itemBDT.getMaTour(), itemBDT.getMaKH(),itemBDT.getSoLuongNguoi(),ngay,
                 itemBDT.getKieuTour(),itemBDT.getKieuKH(),itemBDT.getThanhTien()
                 
        });  
        }
        jTextFieldTongTien.setText(String.valueOf(tongTienTatCa));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMaTour = new javax.swing.JTextField();
        jTextFieldMaKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFielNgayBD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFielSoLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbuttonSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBDT = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxLoai = new javax.swing.JComboBox();
        jButtonSort = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldLoaiTour = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldLoaiKH = new javax.swing.JTextField();
        jPanelVD = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTongTien = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Bảng Đặt Tour");

        jLabel2.setText("Mã Tour");

        jTextFieldMaTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldMaTourMouseExited(evt);
            }
        });

        jTextFieldMaKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldMaKHMouseExited(evt);
            }
        });
        jTextFieldMaKH.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldMaKHInputMethodTextChanged(evt);
            }
        });
        jTextFieldMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaKHActionPerformed(evt);
            }
        });
        jTextFieldMaKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMaKHKeyPressed(evt);
            }
        });

        jLabel3.setText("Mã KH");

        jTextFielNgayBD.setToolTipText("dd/mm/yyyy");

        jLabel4.setText("Ngày Bắt Đầu");

        jTextFielSoLuong.setEditable(false);
        jTextFielSoLuong.setText("1");
        jTextFielSoLuong.setToolTipText("dd/mm/yyyy");

        jLabel5.setText("Số Lượng");

        jbuttonSave.setText("Save");
        jbuttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSaveActionPerformed(evt);
            }
        });

        jTableBDT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tour", "Mã KH", "Số Lượng Người", "Ngày Bắt Đầu", "Kiểu Tour", "Kiểu KH", "Thành Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBDT.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTableBDT);
        jTableBDT.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jLabel6.setText("dd/mm/yyyy");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.orange, null), "Sắp Xếp Danh Sách"));

        jLabel7.setText("Chọn loại sắp xếp");

        jComboBoxLoai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Theo loại Tour", "Theo loại Khách Hàng" }));
        jComboBoxLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxLoaiItemStateChanged(evt);
            }
        });

        jButtonSort.setText("Sort");
        jButtonSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSortMouseClicked(evt);
            }
        });
        jButtonSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSort)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSort)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel8.setText("Kiểu Tour");

        jTextFieldLoaiTour.setEditable(false);

        jLabel9.setText("Kiểu KH");

        jTextFieldLoaiKH.setEditable(false);

        jPanelVD.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanelVDLayout = new javax.swing.GroupLayout(jPanelVD);
        jPanelVD.setLayout(jPanelVDLayout);
        jPanelVDLayout.setHorizontalGroup(
            jPanelVDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        jPanelVDLayout.setVerticalGroup(
            jPanelVDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Tổng Tiền");

        jTextFieldTongTien.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLoaiTour, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldLoaiKH)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFielNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFielSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jbuttonSave))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFielNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbuttonSave)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldLoaiTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFielSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelVD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    int nhapDungMaTour=0;
    int nhapDungMaKH=0;
    BangDatTour bdt=new BangDatTour();
    String[] kieuKH={"Cá Nhân","Tập Thể"};
    double tongTien;
    double donGia;
    private void jbuttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSaveActionPerformed
        // TODO add your handling code here:
        
        if(!jTextFieldMaTour.getText().equals("")){
            for (int i=0;i< jTextFieldMaTour.getText().length();i++) {
                    if(jTextFieldMaTour.getText().charAt(i)<48 ||jTextFieldMaTour.getText().charAt(i)>57 )
                    {  
                        nhapDungMaTour=-1;
                        JOptionPane.showMessageDialog(null, "nhập sai mã tuor");
                        break;
                    } 
            }
            if(nhapDungMaTour==0)
                for (Tour itemTour : dsTour.getListDT()) {
                    if(itemTour.getMaTour()== Integer.parseInt(jTextFieldMaTour.getText()))
                    {
                        nhapDungMaTour=1;
                    }
                }
            if(nhapDungMaTour==1)            
                bdt.setMaTour(Integer.parseInt(jTextFieldMaTour.getText()));
            else JOptionPane.showMessageDialog(null, "mã tour không giống bất kỳ mã nào trong danh sách tour");
            
        }
        else JOptionPane.showMessageDialog(null, "chưa nhập mã tour");
        //
        if(!jTextFieldMaKH.getText().equals("")){
            for (int i=0;i< jTextFieldMaKH.getText().length();i++) {
                    if(jTextFieldMaKH.getText().charAt(i)<48 ||jTextFieldMaKH.getText().charAt(i)>57 )
                    {  
                        nhapDungMaKH=-1;
                        JOptionPane.showMessageDialog(null, "nhập sai mã khách hàng");
                        break;
                    } 
            }
            if(nhapDungMaKH==0)
                 for (KhachHang itemKH : dsKH.getListDT()) {
                    if(itemKH.getMaKH()== Integer.parseInt(jTextFieldMaKH.getText()))
                    {
                        nhapDungMaKH=1;
                    }
                }
            if(nhapDungMaKH==1)
                bdt.setMaKH(Integer.parseInt(jTextFieldMaKH.getText()));
            else JOptionPane.showMessageDialog(null, "mã khách hàng không giống bất kỳ mã nào trong danh sách tour");

        }
        else JOptionPane.showMessageDialog(null, "chưa nhập mã khách hàng");
        int nhapDungNgay=0;
         try {  
               // bdt.setNgayBatDau(new SimpleDateFormat("dd/MM/yyyy").parse(jTextFielNgayBD.getText()));
                String day;
                String[] arrday=new String[3];
                //lưu trữ giá trị kiểm tra tính hợp lệ ngày nhập ,=1 thì nhập đúng ngày.
                 boolean NgayThangNam=false;
               
                day=jTextFielNgayBD.getText();
                if(day.split("/").length!=3){
                   JOptionPane.showMessageDialog(null, "nhập sai ngày bắt đầu.");
                   nhapDungNgay=-1;
                }
                if(nhapDungNgay==0){
                    arrday=day.split("/");
                    NgayThangNam=NgayHopLe(Integer.valueOf(arrday[0]), Integer.valueOf(arrday[1]), Integer.valueOf(arrday[2]));
                
                    if(NgayThangNam==false)
                           JOptionPane.showMessageDialog(null, "nhập sai ngày bắt đầu.");
                    bdt.setNgayBatDau(new Date(Integer.valueOf(arrday[2]),Integer.valueOf(arrday[1]),
                       Integer.valueOf(arrday[0])));
                }
         } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "nhập sai ngày bắt đầu.");
                //return;
            }
        bdt.setSoLuongNguoi(Integer.parseInt(jTextFielSoLuong.getText()));
        if(nhapDungMaKH==1 && nhapDungMaTour==1 && nhapDungNgay==0){
            int thoaManCacGiaTri=0;//kiểm tra xem có nhập bị trùng 1 kh đăng ký 2 tour trong 1 thời gain
            for (BangDatTour itemBDT : dsBangDatTour.getListDT()) {
                if(itemBDT.getMaKH()==bdt.getMaKH() && ( itemBDT.getNgayBatDau().compareTo(bdt.getNgayBatDau()))==0)
                {
                    thoaManCacGiaTri=-1;//1 khách hàng không thể đăng ký 2 tour trong cùng 1 thời gian
                    JOptionPane.showMessageDialog(null, ":"+
                            itemBDT.getMaKH()+" ? "+bdt.getMaKH()+itemBDT.getNgayBatDau()+" ?" +bdt.getNgayBatDau());
                }
                    
            }
            
            if(thoaManCacGiaTri==0){
                tongTien=donGia*bdt.getSoLuongNguoi();
                bdt.setThanhTien(tongTien);
                dsBangDatTour.getListDT().add(bdt);
                tongTienTatCa+=bdt.getThanhTien();
                 jTextFieldTongTien.setText(String.valueOf(tongTienTatCa));
                try {
                    dsBangDatTour.ghiFile("bangdattour.dat");
                } catch (IOException ex) {
                    Logger.getLogger(DatTourPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                ShowResult();
            }
        }
            jTextFieldMaTour.setText("");
            jTextFieldMaKH.setText("");
            jTextFielNgayBD.setText("");
            jTextFielSoLuong.setEditable(false);
            jTextFielSoLuong.setText("1");
            jTextFieldLoaiTour.setText("");
            jTextFieldLoaiKH.setText("");
            bdt =new BangDatTour();
        nhapDungMaTour=0;
         nhapDungMaKH=0;
    }//GEN-LAST:event_jbuttonSaveActionPerformed
    void ShowResult(){
       // Tour lastTour=listTour.get(listTour.size()-1);
        /*(ngaySinh.getMonth()==0)?12:ngaySinh.getMonth(),
                (ngaySinh.getMonth()==0)?ngaySinh.getYear()-1:ngaySinh.getYear())*/
        String ngay="";
       BangDatTour lastBDT=dsBangDatTour.getListDT().get(dsBangDatTour.getListDT().size()-1);
       ngay=lastBDT.getNgayBatDau().getDate()+"/"+((lastBDT.getNgayBatDau().getMonth()==0)?12:lastBDT.getNgayBatDau().getMonth())
               +"/"+((lastBDT.getNgayBatDau().getMonth()==0)?lastBDT.getNgayBatDau().getYear()-1:lastBDT.getNgayBatDau().getYear());
        modelTabel.addRow(new Object[]{//
           lastBDT.getMaTour(), lastBDT.getMaKH(),lastBDT.getSoLuongNguoi(),ngay,lastBDT.getKieuTour(),
            lastBDT.getKieuKH(),lastBDT.getThanhTien()
        });
    }
    public boolean NamNhuan(int year)
    {
         return(((year % 4 == 0) && (year % 100 != 0)) || (year % 400 == 0));
    }

    public boolean NgayHopLe(int ngay, int thang,int nam)
    {
         int[] ngayTrongThang = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
         if(thang <= 0 || thang > 12)
              return false;

         //Năm nhuận tháng 2 29 ngày:
         if(NamNhuan(nam))
              ngayTrongThang[1]++;
         if(nam<=0)
             return false;

         return (ngay > 0 && ngay <= ngayTrongThang[thang - 1]);
    }/* */
    private void jTextFieldMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaKHActionPerformed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_jTextFieldMaKHActionPerformed

    private void jTextFieldMaKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMaKHKeyPressed
        // TODO add your handling code here:
       // JOptionPane.showMessageDialog(null, "vào hàm jTextFieldMaKHKeyPressed");

//          try {
//                for (KhachHang itemKhachHang : dsKH.getListDT()) {
//                    if(itemKhachHang.getMaKH()==Integer.parseInt(jTextFieldMaKH.getText()) )
//                    {
//                        if(itemKhachHang.getKieuKH().equals(kieuKH[0]))
//                        {
//                            bdt.setSoLuongNguoi(1);
//                            jTextFielSoLuong.setEditable(false);
//                        }
//                        if(itemKhachHang.getKieuKH().equals(kieuKH[1]))
//                        {
//                            jTextFielSoLuong.setEditable(true);
//                            
//                        }
//                    }//else jTextFielSoLuong.setEditable(false);
//                }
//            } catch (Exception e) 
//             {
//            }
    }//GEN-LAST:event_jTextFieldMaKHKeyPressed

    private void jTextFieldMaKHInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldMaKHInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldMaKHInputMethodTextChanged

    private void jTextFieldMaKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMaKHMouseExited
        // TODO add your handling code here:
//         JOptionPane.showMessageDialog(null, "vào hàm jTextFieldMaKHMouseExited");
        try {
                for (KhachHang itemKhachHang : dsKH.getListDT()) {
                    if(itemKhachHang.getMaKH()==Integer.parseInt(jTextFieldMaKH.getText()) )
                    {
                        if(itemKhachHang.getKieuKH().equals(kieuKH[0]))
                        {
                            bdt.setSoLuongNguoi(1);
                            bdt.setIntKieuKH(1);
                            jTextFielSoLuong.setEditable(false);
                        }
                        if(itemKhachHang.getKieuKH().equals(kieuKH[1]))
                        {
                            jTextFielSoLuong.setEditable(true);
                            bdt.setIntKieuKH(2);
                            
                        } 
                        jTextFieldLoaiKH.setText(itemKhachHang.getKieuKH());
                        bdt.setKieuKH(itemKhachHang.getKieuKH() );
                    }//else jTextFielSoLuong.setEditable(false);
                }
            } catch (Exception e) 
             {
            }
    }//GEN-LAST:event_jTextFieldMaKHMouseExited

    private void jButtonSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButtonSortActionPerformed
    String loaiSapXep="Theo loại Tour";
    private void jButtonSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSortMouseClicked
        // TODO add your handling code here:
        
        ArrayList<BangDatTour> listTourTemp =new ArrayList<>();
        //listTourTemp=dsBangDatTour.getListDT();
        
//        for (BangDatTour itemBDT : dsBangDatTour.getListDT()) {
//            if(itemBDT.getKieuTour().equals("Dài Ngày")){
//                itemBDT.setIntKieuTour(4);
//                dsBangDatTour.getListDT().set(dsBangDatTour.getListDT().indexOf(itemBDT), itemBDT);
//                 
//            }
//        }
//        try {
//            dsBangDatTour.ghiFile("bangdattour.dat");
//        } catch (IOException ex) {
//            Logger.getLogger(DatTourPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
       listTourTemp.addAll(dsBangDatTour.getListDT());
//        DefaultTableModel tableModel=(DefaultTableModel)jTableBDT.getModel();//new DefaultTableModel();//    
//        String ngay;
//        jTableBDT.setModel(tableModel);
//        for (BangDatTour itemBDT : listTourTemp) { 
//            System.out.print("\n "+itemBDT.getKieuTour()+"  : "+itemBDT.getIntKieuTour());
//            ngay=itemBDT.getNgayBatDau().getDate()+"/"+((itemBDT.getNgayBatDau().getMonth()==0)?12:itemBDT.getNgayBatDau().getMonth())
//               +"/"+((itemBDT.getNgayBatDau().getMonth()==0)?itemBDT.getNgayBatDau().getYear()-1:itemBDT.getNgayBatDau().getYear());
//             tableModel.addRow(new Object[]{//
//           itemBDT.getMaTour(), itemBDT.getMaKH(),itemBDT.getSoLuongNguoi(),ngay,
//                 itemBDT.getKieuTour(),itemBDT.getKieuKH(),itemBDT.getThanhTien()
//                 
//        });
//            
//        } 
       // if(jComboBoxLoai.get)
       
//Theo loại Khách Hàng
        if(loaiSapXep.equals("Theo loại Tour")){
            Collections.sort(listTourTemp, new KieuTourComparator());
             jPanelVD.removeAll();
             jPanelVD.setLayout(new BorderLayout());
             JPanel bdtpn=new bangDatTourPanel(listTourTemp);
             jPanelVD.add(bdtpn);
             jPanelVD.validate();
             jPanelVD.repaint();
        }
        else{
            Collections.sort(listTourTemp, new KieuKHComparator());
            jPanelVD.removeAll();
            jPanelVD.setLayout(new BorderLayout());
            JPanel bdtpn=new bangDatTourPanel(listTourTemp);
            jPanelVD.add(bdtpn);
            jPanelVD.validate();
            jPanelVD.repaint();
        }
        
//        int k=modelTabel.getRowCount();
//        jTableBDT.removeRowSelectionInterval(0, k);
//        for (int i=1;i<k;i++) {
//            modelTabel.removeRow(i);
//        }
       // jTableBDT.add
//        jTableBDT.setModel(modelTabel);
    }//GEN-LAST:event_jButtonSortMouseClicked

    private void jTextFieldMaTourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMaTourMouseExited
        // TODO add your handling code here:
         try {
                for (Tour itemTour : dsTour.getListDT()) {
                    if(itemTour.getMaTour()==Integer.parseInt(jTextFieldMaTour.getText()) )
                    {
                       
                        jTextFieldLoaiTour.setText(itemTour.getKieuTour());
                        bdt.setKieuTour(itemTour.getKieuTour());
                        donGia=itemTour.getDonGia();
                        switch(itemTour.getKieuTour()){
                            case "1 Ngày":bdt.setIntKieuTour(1);break;
                            case "Dưới 5 Ngày":bdt.setIntKieuTour(2);break;
                            case "Dưới 7 Ngày":bdt.setIntKieuTour(3);break;
                            case "Dài Ngày":bdt.setIntKieuTour(4);break;
                            default: bdt.setIntKieuTour(0);break;
                                
                        }
                    }//else jTextFielSoLuong.setEditable(false);
                }
            } catch (Exception e) 
             {
            }
    }//GEN-LAST:event_jTextFieldMaTourMouseExited

    private void jComboBoxLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxLoaiItemStateChanged
        // TODO add your handling code here:
         if(evt.getStateChange()==ItemEvent.SELECTED){
             loaiSapXep=jComboBoxLoai.getSelectedItem().toString();
         }
    }//GEN-LAST:event_jComboBoxLoaiItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSort;
    private javax.swing.JComboBox jComboBoxLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelVD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBDT;
    private javax.swing.JTextField jTextFielNgayBD;
    private javax.swing.JTextField jTextFielSoLuong;
    private javax.swing.JTextField jTextFieldLoaiKH;
    private javax.swing.JTextField jTextFieldLoaiTour;
    private javax.swing.JTextField jTextFieldMaKH;
    private javax.swing.JTextField jTextFieldMaTour;
    private javax.swing.JTextField jTextFieldTongTien;
    private javax.swing.JButton jbuttonSave;
    // End of variables declaration//GEN-END:variables
}
