/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ItemEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DocGhiFile;
import model.KhachHang;
import model.Tour;

/**
 *
 * @author NCT99
 */
public class KhachHangPanel extends javax.swing.JPanel {

    /**
     * Creates new form KhachHangPanel
     *
     */
     DocGhiFile<KhachHang> listKHTuFile;
        
         DefaultTableModel modelTabel ;
        int maKHCuoi=100;
  
    public KhachHangPanel() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        
        listKHTuFile =new DocGhiFile<>();
        
        modelTabel=(DefaultTableModel) jTableKH.getModel();
        
        listKHTuFile.docfile("khachhang.dat");
        for (KhachHang itemKH : listKHTuFile.getListDT()) {
             modelTabel.addRow(new Object[]{//
           itemKH.getMaKH(), itemKH.getTenKH(),itemKH.getKieuKH()
        });
        }
        if(listKHTuFile.getListDT().size()-1>=0)
         maKHCuoi=listKHTuFile.getListDT().get(listKHTuFile.getListDT().size()-1).getMaKH();
        jTextFieldMaKH.setText((String.valueOf(maKHCuoi+1)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelMaKH = new javax.swing.JLabel();
        jTextFieldMaKH = new javax.swing.JTextField();
        jLabelTenKH = new javax.swing.JLabel();
        jTextFieldTenkH = new javax.swing.JTextField();
        jLabelKieuKH = new javax.swing.JLabel();
        jComboBoxKieukH = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKH = new javax.swing.JTable();
        jButtonSaveKH = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Khách Hàng");

        jLabelMaKH.setText("Mã KH");

        jTextFieldMaKH.setEditable(false);

        jLabelTenKH.setText("Tên");

        jLabelKieuKH.setText("Kiểu KH");

        jComboBoxKieukH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cá Nhân", "Tập Thể" }));
        jComboBoxKieukH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxKieukHItemStateChanged(evt);
            }
        });

        jTableKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã kH", "Tên kH", "Kiểu KH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableKH);

        jButtonSaveKH.setText("Save");
        jButtonSaveKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSaveKH)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMaKH)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelTenKH)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldTenkH, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addComponent(jLabelKieuKH)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxKieukH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaKH)
                    .addComponent(jTextFieldMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTenKH)
                    .addComponent(jTextFieldTenkH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKieuKH)
                    .addComponent(jComboBoxKieukH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSaveKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    String kieuKH="Cá Nhân";
    private void jButtonSaveKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveKHActionPerformed
        // TODO add your handling code here:
        KhachHang kh =new KhachHang();
        kh.setKieuKH(kieuKH);
        kh.setMaKH(++maKHCuoi);
        kh.setTenKH(jTextFieldTenkH.getText() );
        
        //listTour.add(tour);
        listKHTuFile.getListDT().add(kh);
        //jTableTour.setValueAt(listTour.get(0).getKieuTour(), 0, 1);
        try {
                    listKHTuFile.ghiFile("khachhang.dat");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "ghi file bị lỗi:"+ex.toString());
        }
        ShowResult();
        
        jTextFieldTenkH.setText("");
        jTextFieldMaKH.setText((String.valueOf(maKHCuoi+1)));
    }//GEN-LAST:event_jButtonSaveKHActionPerformed
    void ShowResult(){
       // Tour lastTour=listTour.get(listTour.size()-1);
       KhachHang lastKH=listKHTuFile.getListDT().get(listKHTuFile.getListDT().size()-1);
        modelTabel.addRow(new Object[]{//
           lastKH.getMaKH(), lastKH.getTenKH(),lastKH.getKieuKH()
        });
    }
    private void jComboBoxKieukHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxKieukHItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED){
             kieuKH=jComboBoxKieukH.getSelectedItem().toString();
         }
    }//GEN-LAST:event_jComboBoxKieukHItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSaveKH;
    private javax.swing.JComboBox jComboBoxKieukH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelKieuKH;
    private javax.swing.JLabel jLabelMaKH;
    private javax.swing.JLabel jLabelTenKH;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKH;
    private javax.swing.JTextField jTextFieldMaKH;
    private javax.swing.JTextField jTextFieldTenkH;
    // End of variables declaration//GEN-END:variables
}
