/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.awt.event.ItemEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DSTour;
import model.DocGhiFile;
import model.Tour;


/**
 *
 * @author NCT99
 */
public class TourPanel extends javax.swing.JPanel {
//    DSTour dstour =new DSTour();
        DocGhiFile<Tour> listTourTuFile;
        // ArrayList<Tour> listTour;
         DefaultTableModel modelTabel ;
        int maTourCuoi=1000;
           
    /**
     * Creates new form TourPanel
     */
    public TourPanel() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();//listTour=new ArrayList<>();
        listTourTuFile =new DocGhiFile<>();
        
        modelTabel=(DefaultTableModel) jTableTour.getModel();
        
        listTourTuFile.docfile("tour.dat");
        //listTour =listTourTuFile.getListDT();
        for (Tour itemTour : listTourTuFile.getListDT()) {
             modelTabel.addRow(new Object[]{//
           itemTour.getMaTour() , itemTour.getKieuTour(),itemTour.getThongTinTour(),itemTour.getDonGia()
        });
        }
        if(listTourTuFile.getListDT().size()-1>=0)
         maTourCuoi=listTourTuFile.getListDT().get(listTourTuFile.getListDT().size()-1).getMaTour();
        jTextFieldMaTour.setText((String.valueOf(maTourCuoi+1)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMaTour = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxKieuTour = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDonGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaThongTinTour = new javax.swing.JTextArea();
        jButtonSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTour = new javax.swing.JTable();
        jPanelXoaTour = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTourXoa = new javax.swing.JTextField();
        jButtonXoaTour = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tour");

        jLabel2.setText("Mã Tour");

        jTextFieldMaTour.setEditable(false);
        jTextFieldMaTour.setText("1000");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Kiểu Tour");

        jComboBoxKieuTour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 Ngày", "Dưới 5 Ngày", "Dưới 7 Ngày", "Dài Ngày" }));
        jComboBoxKieuTour.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxKieuTourItemStateChanged(evt);
            }
        });

        jLabel4.setText("Đơn Giá");

        jTextFieldDonGia.setText("0");

        jLabel5.setText("Thông Tin Tour");
        jLabel5.setFocusable(false);

        jTextAreaThongTinTour.setColumns(20);
        jTextAreaThongTinTour.setRows(5);
        jTextAreaThongTinTour.setToolTipText("nhập mô tả");
        jTextAreaThongTinTour.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaThongTinTour);

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jTableTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tour", "Kiểu Tour", "Thông Tin", "Đơn Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableTour);

        jPanelXoaTour.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null), "Xóa Tour Theo Mã"));

        jLabel7.setText("mã Tour");

        jButtonXoaTour.setText("Xóa");
        jButtonXoaTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaTourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelXoaTourLayout = new javax.swing.GroupLayout(jPanelXoaTour);
        jPanelXoaTour.setLayout(jPanelXoaTourLayout);
        jPanelXoaTourLayout.setHorizontalGroup(
            jPanelXoaTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelXoaTourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTourXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButtonXoaTour)
                .addContainerGap())
        );
        jPanelXoaTourLayout.setVerticalGroup(
            jPanelXoaTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelXoaTourLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelXoaTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldTourXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelXoaTourLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonXoaTour)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonSave))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxKieuTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelXoaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSave)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxKieuTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelXoaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

//    Vector vTieuDe =new Vector();
//    Vector vNoiDung =new Vector();
//    Vector vDong =new Vector();
    
    
    String kieuTour="1 Ngày";
    
    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        int kiemTraDonGia=1;//kiểm tra xem text nhập vào trường đơn giá có hợp lệ ko.
        int coDauCham=0;//kiểm tra xem có mấy dấu chấm, 1 dấu là thỏa mãn.
        
        for (int i=0;i< jTextFieldDonGia.getText().length();i++) {
                if(jTextFieldDonGia.getText().charAt(i)<48 ||jTextFieldDonGia.getText().charAt(i)>57 )
                {  
                    if(jTextFieldDonGia.getText().charAt(i)==46){
                        if(coDauCham==1){
                            coDauCham=2;
                            kiemTraDonGia=-1;
                            break;
                        }
                        coDauCham=1;
                        continue;
                     }
                    kiemTraDonGia=-1;
                    break;
                }
                
        }
        if(kiemTraDonGia==1){
        Tour tour =new Tour();
        tour.setKieuTour(kieuTour);
        tour.setMaTour(++maTourCuoi);
        tour.setDonGia(Double.valueOf(jTextFieldDonGia.getText()) );
        tour.setThongTinTour(jTextAreaThongTinTour.getText());
        //listTour.add(tour);
        listTourTuFile.getListDT().add(tour);
        //jTableTour.setValueAt(listTour.get(0).getKieuTour(), 0, 1);
        try {
                    listTourTuFile.ghiFile("tour.dat");
        } catch (IOException ex) {
                    Logger.getLogger(TourPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        ShowResult();
        
        jTextAreaThongTinTour.setText("");
        jTextFieldDonGia.setText("0");
        jTextFieldMaTour.setText((String.valueOf(maTourCuoi+1)));
        
       
        }
        else{
            JOptionPane.showMessageDialog(null, "Đơn giá là kiểu số thực!!!!", "Lỗi Nhập", 1);
            jTextAreaThongTinTour.setText("");
            jTextFieldDonGia.setText("0");
            jTextFieldMaTour.setText((String.valueOf(maTourCuoi+1)));
             kiemTraDonGia=1;
            coDauCham=0;
        }
         kiemTraDonGia=1;
        coDauCham=0;
    }//GEN-LAST:event_jButtonSaveActionPerformed
    void ShowResult(){
       // Tour lastTour=listTour.get(listTour.size()-1);
       Tour lastTour=listTourTuFile.getListDT().get(listTourTuFile.getListDT().size()-1);
        modelTabel.addRow(new Object[]{//
           lastTour.getMaTour() , lastTour.getKieuTour(),lastTour.getThongTinTour(),lastTour.getDonGia()
        });
    }
    private void jComboBoxKieuTourItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxKieuTourItemStateChanged
        // TODO add your handling code here:
         if(evt.getStateChange()==ItemEvent.SELECTED){
             kieuTour=jComboBoxKieuTour.getSelectedItem().toString();
         }
    }//GEN-LAST:event_jComboBoxKieuTourItemStateChanged

    private void jButtonXoaTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaTourActionPerformed
        // TODO add your handling code here:
        int maXoa=0;
        //if(Integer.parseInt(jTextFieldTourXoa.getText()))
        try {
            maXoa=Integer.parseInt(jTextFieldTourXoa.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"nhập số nguyên.");
            return;
        }
        int coMaMuonXoa=-1;
        for (Tour item : listTourTuFile.getListDT()) {
            if(maXoa == item.getMaTour()){   
                listTourTuFile.getListDT().remove(item); 
                coMaMuonXoa=1;
                try {
                    listTourTuFile.ghiFile("tour.dat");
                } catch (IOException ex) {
                    Logger.getLogger(TourPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            }
        } 
        //JOptionPane.showMessageDialog(null, "tổng hàng:"+modelTabel.getRowCount());
        if(coMaMuonXoa==1)       
        for (int i = 0; i < modelTabel.getRowCount(); i++) {
            if((int)modelTabel.getValueAt(i,0)==maXoa);
            {  
               // modelTabel.removeRow(i);
                
              //  jTableTour.removeRowSelectionInterval(i, i);
                
                break;
            }
        }
    }//GEN-LAST:event_jButtonXoaTourActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonXoaTour;
    private javax.swing.JComboBox jComboBoxKieuTour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelXoaTour;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTour;
    private javax.swing.JTextArea jTextAreaThongTinTour;
    private javax.swing.JTextField jTextFieldDonGia;
    private javax.swing.JTextField jTextFieldMaTour;
    private javax.swing.JTextField jTextFieldTourXoa;
    // End of variables declaration//GEN-END:variables

//     public void ghiFile(String filename) throws FileNotFoundException, IOException{
////          
//             FileOutputStream fout = new FileOutputStream(filename);
//            ObjectOutputStream out =new ObjectOutputStream(fout);
//            out.writeObject(listTour);           
//            out.close();
//           fout.close();
//        }
//    public void docfile(String filename) throws FileNotFoundException, IOException, ClassNotFoundException{
//            try{ 
//            FileInputStream fin =new FileInputStream(filename);
//            ObjectInputStream obin =new ObjectInputStream(fin);           
//            listTour=(ArrayList)obin.readObject();
//            obin.close();//fin.close();
//            }catch(Exception e){
//                
//                System.out.print("\n!!!Lỗi :"+e);
//            }
//        }
}
